/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AirlineReservation;

import AirlineReservation.PaymentManager;
import javax.swing.JOptionPane;
/**
 *
 * @author Anubhav
 */
public class PaymentDetails extends javax.swing.JFrame {
    String path;
    PaymentManager pm;
    String ticket;
    /**
     * Creates new form PaymentDetails
     */
    public PaymentDetails(String ticket) {
        /*
        Unresolvable issue: Even though CardDatabase.txt lies in the same package, it returns a FileNotFoundException
        when called using just 'CardDatabase.txt', unlike FlightDetals.csv or UserInfo.csv
        adjust code before running. This has been temporarily adjusted in a FileNotFoundException handling in PaymentManager.java
        */
        
        this.path = "PaymentCardDatabase.csv";
        
        this.pm = new PaymentManager();
        initComponents();
        this.ticket = ticket;
    }
    public PaymentDetails(){
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCardNumber = new javax.swing.JTextField();
        txtCardname = new javax.swing.JTextField();
        txtExpiryDate = new javax.swing.JTextField();
        txtCVV = new javax.swing.JTextField();
        btProceed = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbPaymentGateway = new javax.swing.JLabel();
        lbCardnumber = new javax.swing.JLabel();
        lbCardName = new javax.swing.JLabel();
        lbExpiryDate = new javax.swing.JLabel();
        lbCVV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));

        txtCardNumber.setBackground(new java.awt.Color(51, 51, 51));
        txtCardNumber.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCardNumber.setForeground(new java.awt.Color(255, 255, 255));

        txtCardname.setBackground(new java.awt.Color(51, 51, 51));
        txtCardname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCardname.setForeground(new java.awt.Color(255, 255, 255));

        txtExpiryDate.setBackground(new java.awt.Color(51, 51, 51));
        txtExpiryDate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtExpiryDate.setForeground(new java.awt.Color(255, 255, 255));

        txtCVV.setBackground(new java.awt.Color(51, 51, 51));
        txtCVV.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtCVV.setForeground(new java.awt.Color(255, 255, 255));

        btProceed.setBackground(new java.awt.Color(204, 255, 255));
        btProceed.setText("Proceed");
        btProceed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProceedActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        lbPaymentGateway.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbPaymentGateway.setForeground(new java.awt.Color(0, 204, 204));
        lbPaymentGateway.setText("PAYMENT GATEWAY");

        lbCardnumber.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbCardnumber.setForeground(new java.awt.Color(0, 153, 153));
        lbCardnumber.setText("CARD NUMBER");

        lbCardName.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbCardName.setForeground(new java.awt.Color(0, 153, 153));
        lbCardName.setText("CARDNAME");

        lbExpiryDate.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbExpiryDate.setForeground(new java.awt.Color(0, 153, 153));
        lbExpiryDate.setText("EXPIRY DATE");

        lbCVV.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        lbCVV.setForeground(new java.awt.Color(0, 153, 153));
        lbCVV.setText("CVV");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(lbPaymentGateway, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCardnumber)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCardNumber)
                                .addComponent(txtCardname)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbExpiryDate))
                                    .addGap(74, 74, 74)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbCVV)
                                        .addComponent(txtCVV, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))
                            .addComponent(lbCardName)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lbPaymentGateway, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(lbCardnumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lbCardName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCardname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbExpiryDate)
                    .addComponent(lbCVV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btProceed)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProceedActionPerformed
        // TODO add your handling code here:
        String cardnumber = txtCardNumber.getText();
        String cardname =  txtCardname.getText();
        String expirydate = txtExpiryDate.getText();
        String cvv = txtCVV.getText();
        
        if(pm.checkCard(cardnumber, cardname, cvv, expirydate, path)){
             JOptionPane.showMessageDialog(null, "Payment Successful", "Generating Ticket", JOptionPane.INFORMATION_MESSAGE);
             new generateTicket(ticket).setVisible(true);
             this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Wrong Entry", "Failure", JOptionPane.INFORMATION_MESSAGE);
            new PaymentDetails(ticket).setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_btProceedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btProceed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbCVV;
    private javax.swing.JLabel lbCardName;
    private javax.swing.JLabel lbCardnumber;
    private javax.swing.JLabel lbExpiryDate;
    private javax.swing.JLabel lbPaymentGateway;
    private javax.swing.JTextField txtCVV;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtCardname;
    private javax.swing.JTextField txtExpiryDate;
    // End of variables declaration//GEN-END:variables
}
